### ISSUE TITLE
Option to install docker-compose

### ISSUE THREAD

**Issue by rohankrishnadev** [robertdebock/ansible-role-docker_ce#5]
**Is your feature request related to a problem? Please describe.**
Having installed docker, I either have to manually install docker-compose or pass it as a parameter to [python_pip](https://github.com/robertdebock/ansible-role-python_pip) role.

**Describe the solution you'd like**
A task to install docker-compose with pip; the task can be controlled by a default variable (default vaule of false). Installing with pip will give you the latest stable version.

**Describe alternatives you've considered**
You could pass docker-compose as a parameter to [python_pip](https://github.com/robertdebock/ansible-role-python_pip) role. However, it would make logical sense to add it to this role instead.

**Additional context**
N/A

**Comment by robertdebock** [comment]
Thanks for the feedback, I'll work on it.

**Comment by robertdebock** [comment]
I've just checked the code, there is a [task](https://github.com/robertdebock/ansible-role-docker_ce/blob/master/tasks/main.yml#L43) to install [`docker-compose` using `pip`](https://github.com/robertdebock/ansible-role-docker_ce/blob/master/vars/main.yml#L71).

I've also started (a Fedora) instance and tried to run docker-compose, which seems to work:
```
molecule test --destroy=never
...
molecule login
...
[root@dockerce-fedora-latest /]# docker-compose --version
docker-compose version 1.25.0, build b42d419
```

I'll close the issue because I think the role works as you want it to work. Let me know (by re-opening the issue) if further work is required.
